server:
  port: 8081

spring:
  application:
    name: "solicitudes-service"
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  devtools:
    add-properties: false
  aop:
    auto: true
    proxy-target-class: true
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: ${JWT_JWK_SET_URI:http://localhost:8080/.well-known/jwks.json}
#          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8080}

# Database configuration
  r2dbc:
    url: r2dbc:postgresql://${R2DBC_HOST}:${R2DBC_PORT}/${R2DBC_DATABASE}
    username: ${R2DBC_USERNAME}
    password: ${R2DBC_PASSWORD}
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
      validation-query: SELECT 1
  
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: false
  

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}

#logging:
#  level:
#    co.com.crediya.solicitudes: DEBUG
#    org.springframework.r2dbc: DEBUG
#    org.springframework.security: DEBUG
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8081"

# Authentication service configuration
auth-service:
  base-url: ${AUTH_SERVICE_BASE_URL}
  endpoints:
    api-base: ${AUTH_SERVICE_ENDPOINTS_API_BASE}
    user-by-document: ${AUTH_SERVICE_ENDPOINTS_USER_BY_DOCUMENT}

# Resilience4j configuration
resilience4j:
  circuitbreaker:
    instances:
      auth-service:
        sliding-window-size: 20
        failure-rate-threshold: 80
        minimum-number-of-calls: 10
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        register-health-indicator: true
  retry:
    instances:
      auth-service:
        max-attempts: 3
        wait-duration: 8s
        exponential-backoff-multiplier: 1
        retry-exceptions:
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - java.net.ConnectException
  timelimiter:
    instances:
      auth-service:
        timeout-duration: 30s


