package co.com.crediya.solicitudes.api.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ApplicationResponse {
    
    private Long requestId;
    private String documentId;
    private BigDecimal amount;
    private Integer term;
    private String email;
    private Long statusId;
    private Long loanTypeId;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    
    // Additional fields for response enrichment
    private String statusName;
    private String loanTypeName;
    private String statusDescription;
    
    // Getters and setters are generated by Lombok
}
